# Generated by Django 4.1.3 on 2022-11-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std_address',
        ),
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Info.student'),
            preserve_default=False,
        ),
    ]
